<#
.SYNOPSIS
  Concatenate MP4 clips and prepend a 3-second title card using FFmpeg.

.DESCRIPTION
  - Builds a concat demuxer list file (mylist.txt)
  - Concats clips losslessly when compatible (-c copy) using concat demuxer
  - Probes merged output for width/height/fps
  - Creates title card via lavfi color source + drawtext
  - Prepends title to merged video and encodes final output

REQUIREMENTS
  - ffmpeg and ffprobe available on PATH

REFERENCES
  - FFmpeg concat demuxer usage: https://trac.ffmpeg.org/wiki/Concatenate [1](https://trac.ffmpeg.org/wiki/Concatenate)
  - drawtext usage and centering: https://stackoverflow.com/questions/17623676/text-on-video-ffmpeg [4](https://stackoverflow.com/questions/17623676/text-on-video-ffmpeg)
  - creating blank colour screen with text (lavfi color + drawtext): https://stackoverflow.com/questions/22710099/ffmpeg-create-blank-screen-with-text-video [3](https://stackoverflow.com/questions/22710099/ffmpeg-create-blank-screen-with-text-video)
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# -------------------------
# Configuration
# -------------------------
$SrcRoot   = "C:\temp\BashFileWalking 02.mp4"
$TempDir   = "C:\temp"
$ListFile  = Join-Path $TempDir "mylist.txt"
$MergedMp4 = Join-Path $TempDir "merged.mp4"
$DestFile  = Join-Path $TempDir "golf_range_18_09_2023.mp4"

$TitleText     = "Badgers in the garden - 2 April 2026"
$TitleDuration = 3

# Font handling:
# Option A (recommended on Windows): use fontfile
$FontFile = "C:/Windows/Fonts/arial.ttf"
# Option B: use font name (requires fontconfig/libfreetype support)
$FontName = "Arial"

# If your system struggles with font=, set $UseFontFile = $true
$UseFontFile = $true

# Title styling
$FontSize = 80
$FontColor = "white"

# Video encoding settings for final output
$VideoCodec = "libx264"
$PixelFormat = "yuv420p"
$AudioCodec = "aac"

# Add silent audio during the title segment so the output has continuous audio track
$AddSilentAudioForTitle = $true
$AudioSampleRate = 48000
$AudioChannels = 2

# -------------------------
# Helpers
# -------------------------
function Assert-ToolExists([string]$toolName) {
    $cmd = Get-Command $toolName -ErrorAction SilentlyContinue
    if (-not $cmd) {
        throw "Required tool '$toolName' not found on PATH."
    }
}

function Invoke-External([string]$exe, [string[]]$argList) {
    Write-Host "`n> $exe $($argList -join ' ')" -ForegroundColor Cyan

    $p = Start-Process `
        -FilePath $exe `
        -ArgumentList $argList `
        -NoNewWindow `
        -Wait `
        -PassThru

    if ($p.ExitCode -ne 0) {
        throw "$exe failed with exit code $($p.ExitCode)."
    }
}
function Get-VideoProps([string]$filePath) {
    # width, height, and r_frame_rate are commonly used for this kind of matching
    $probeArgs = @(
        "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=width,height,r_frame_rate",
        "-of", "default=nw=1:nk=1",
        $filePath
    )

    $output = & ffprobe @probeArgs
    if ($LASTEXITCODE -ne 0) { throw "ffprobe failed for $filePath" }

    # Expected output lines: width, height, r_frame_rate (e.g., 1920, 1080, 30000/1001)
if ($output.Count -lt 3) { throw "Unexpected ffprobe output for $($filePath): $($output -join ' | ')" }

    $width  = [int]$output[0]
    $height = [int]$output[1]
    $rate   = $output[2].Trim()

    # Convert fractional frame rate to a decimal string FFmpeg accepts (approx)
    # (FFmpeg also accepts fractions directly, but using a rounded decimal is fine.)
    $fps = $rate
    if ($rate -match "^(\d+)\/(\d+)$") {
        $num = [double]$Matches[1]
        $den = [double]$Matches[2]
        if ($den -ne 0) {
            $fps = [Math]::Round(($num / $den), 3).ToString("0.###")
        }
    }

    return [pscustomobject]@{ Width=$width; Height=$height; Fps=$fps; RateRaw=$rate }
}

# -------------------------
# Main
# -------------------------
Assert-ToolExists "ffmpeg"
Assert-ToolExists "ffprobe"

if (-not (Test-Path $TempDir)) {
    New-Item -ItemType Directory -Path $TempDir | Out-Null
}

# Gather clips
$clips = @(
    Get-ChildItem -Path $SrcRoot -Filter "*.mp4" | Sort-Object Name
)

if ($clips.Count -eq 0) {
    throw "No .mp4 files found in '$SrcRoot'."
}

Write-Host "Found $($clips.Count) clips:" -ForegroundColor Green
$clips | ForEach-Object { Write-Host " - $($_.FullName)" }

# Write concat list file (concat demuxer format: file '...') [1](https://trac.ffmpeg.org/wiki/Concatenate)[2](https://cloudinary.com/guides/video-effects/ffmpeg-concat)
"# Autogenerated by concat_with_title.ps1" | Out-File -FilePath $ListFile -Encoding ascii

# Write concat list file (ASCII, no BOM, forward slashes, no comments)
"" | Out-File -FilePath $ListFile -Encoding ascii

foreach ($c in $clips) {
    $path = ($c.FullName -replace '\\', '/')
    "file '$path'" | Out-File -FilePath $ListFile -Encoding ascii -Append
}
Write-Host "`nWrote list file: $ListFile" -ForegroundColor Green
#Get-Content $ListFile -Raw | Format-Hex
Get-Content $ListFile


# Step 1: Concat clips quickly when compatible (-c copy) using concat demuxer [1](https://trac.ffmpeg.org/wiki/Concatenate)[2](https://cloudinary.com/guides/video-effects/ffmpeg-concat)
Invoke-External "ffmpeg" @(
    "-y",
    "-f", "concat",
    "-safe", "0",
    "-i", $ListFile,
    "-c", "copy",
    $MergedMp4
)
Write-Host "Merged clip created: $MergedMp4" -ForegroundColor Green

# Probe merged output to match title dimensions/fps
$props = Get-VideoProps $MergedMp4
Write-Host ("Detected merged properties: {0}x{1} @ {2} fps (raw: {3})" -f `
    $props.Width, $props.Height, $props.Fps, $props.RateRaw) -ForegroundColor Green

# Build drawtext clause (either fontfile=... or font=...)
# drawtext filter usage [4](https://stackoverflow.com/questions/17623676/text-on-video-ffmpeg)[3](https://stackoverflow.com/questions/22710099/ffmpeg-create-blank-screen-with-text-video)
$drawTextCommon = "text='$TitleText':fontsize=$FontSize:fontcolor=$FontColor:x=(w-text_w)/2:y=(h-text_h)/2"
if ($UseFontFile) {
    $drawText = "drawtext=fontfile='$FontFile':$drawTextCommon"
} else {
    $drawText = "drawtext=font='$FontName':$drawTextCommon"
}

# Build title input(s)
# solid colour background with lavfi color + drawtext [3](https://stackoverflow.com/questions/22710099/ffmpeg-create-blank-screen-with-text-video)[4](https://stackoverflow.com/questions/17623676/text-on-video-ffmpeg)
$titleVideoLavfi = "color=c=black:s=$($props.Width)x$($props.Height):d=$TitleDuration:r=$($props.Fps)"

if ($AddSilentAudioForTitle) {
    $silentAudioLavfi = "anullsrc=channel_layout=stereo:sample_rate=$AudioSampleRate:d=$TitleDuration"
}

# Step 2: Prepend title + encode final output
# We use concat filtergraph (re-encodes) to stitch title segment to merged video.tps://wavespeed.ai/blog/posts/blog-how-to-merge-concatenate-videos-ffmpeg/)[6](https://ffmpeg.run/posts/how-to-merge-videos-using-ffmpeg)
if ($AddSilentAudioForTitle) {
    $filterComplex = @"
[0:v]$drawText[vtitle];
[vtitle][1:a][2:v][2:a]concat=n=2:v=1:a=1[outv][outa]
"@.Trim()

    Invoke-External "ffmpeg" @(
        "-y",
        "-f", "lavfi", "-i", $titleVideoLavfi,
        "-f", "lavfi", "-i", $silentAudioLavfi,
        "-i", $MergedMp4,
        "-filter_complex", $filterComplex,
        "-map", "[outv]",
        "-map", "[outa]",
        "-c:v", $VideoCodec,
        "-pix_fmt", $PixelFormat,
        "-c:a", $AudioCodec,
        $DestFile
    )
} else {
    $filterComplex = @"
[0:v]$drawText[vtitle];
[vtitle][1:v]concat=n=2:v=1:a=0[outv]
"@.Trim()

    Invoke-External "ffmpeg" @(
        "-y",
        "-f", "lavfi", "-i", $titleVideoLavfi,
        "-i", $MergedMp4,
        "-filter_complex", $filterComplex,
        "-map", "[outv]",
        "-c:v", $VideoCodec,
        "-pix_fmt", $PixelFormat,
        "-c:a", $AudioCodec,
        $DestFile
    )
}

Write-Host "`nDone. Final output: $DestFile" -ForegroundColor Green
