# Path to files (excluding the actual files)
VIDEO_PATH="/mnt/c/temp/downloads/videos"

# Input video file
INPUT="Camo Studio Recording 2026-02-22 14-29-05.mp4"

# Audio offset in seconds (e.g. -2.5 or +0.5)
OFFSET="+0.5"
