# Convert a .MOV video file to an .MP4 format using ffmpeg.
# The output file is saved in the same directory as the input file, 
# with a randomized name to avoid overwriting.
#
# Dependencies:
# - run this in bash on unix, mac, wsl, but not in git bash on windows.
# - ffmpeg: A command-line tool for processing video and audio files.
#
# Usage:
# - Ensure ffmpeg is installed and available in your system's PATH.
# - Update the variable `f` with the path to your .MOV file.
# - Run the script to generate the .MP4 file.
#
# Example:
# f="path/to/your_video.MOV"
# ./convert_mov_to_mp4.sh
#
# Output:
# - The converted .MP4 file will be saved in the same directory as the input file.

f="test_artifacts/temp_assets/x_8263.MOV"

# Convert the .MOV file to .MP4 format
# The output file name is generated by appending a random number to the original 
# file name (excluding the extension).
ffmpeg -i "$f" "${f%.*}_$((RANDOM+RANDOM)).mp4"
